[www]
user = www-data
group = www-data

; NGINXから9000番でFastCGI接続を受け付ける(0.0.0.0 = コンテナ内の全インターフェース)
listen = 0.0.0.0:9000
listen.owner = www-data
listen.group = www-data

; ワーカープロセスの数を必要に応じて増減させる方式
pm = dynamic
pm.max_children = 10
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 5

; コンテナの環境変数をPHP側からgetenv()等で読めるようにする
clear_env = no
